version: "3.9"
services:
  csvserver:
     image: "infracloudio/csvserver:latest"
     volumes:
      -  C:\test\inputFile:/csvserver/inputdata:rw  
     ports:
      - "9300:9300"
     
     environment:
      CSVSERVER_BORDER: Orange
  Prometheus:
     image: "prom/prometheus:v2.22.0"
     command: "--config.file=/etc/prometheus/prometheus.yml"
     ports: 
      - "9090:9090"      